monolog:
    handlers:
        custom_log:
            type: stream
            path: "%kernel.logs_dir%kernel.custom%.log"
            level: notice
            channels: ['coen']
        coen:
            type: stream
            path: "%kernel.logs_dir%/coen.log"
            level: debug
            channels: ["coen"]
